name: NPM
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: NPM
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - run: |
          npm install
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}