name: NPM
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: NPM
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Check version change
        if: ${{ github.event_name == 'push' }}
        run: |
          version_changed=$(git diff HEAD^ HEAD package.json | grep '^\+.*"version":' | wc -l)
          if [ "$version_changed" -ne 0 ]; then
            echo "Version changed, triggering workflow..."
            exit 0
          else
            echo "Version not changed, skipping workflow..."
            exit 1
          fi
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Run
        run: |
          npm install
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}